name: condaenv
channels:
  - fastai
  - conda-forge
dependencies:
  - albumentations=1.0.3
  - catboost=0.26.1
  - fastai=2.5.0
  - imageio=2.9.0
  - keras=2.6.0
  - loguru=0.5.3
  - mkl=2020.4
  - numpy=1.20.3
  - numba=0.54.1
  - pandas=1.2.5
  - pillow=8.2.0
  - pip=20.3.4
  - pytest=6.2.4
  - python=3.9.7
  - pytorch-cpu=1.8.0
  - pytorch-lightning=1.4.1
  - scikit-image=0.18.2
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - segmentation-models-pytorch=0.2.1
  - tiledb=2.3.2
  - timm=0.4.12
  - torchvision=0.9.1
  - tqdm=4.62.0
  - xarray=0.19.0
  - pip:
    - crfseg==1.0.0
    - lightning-flash[image]==0.5.0
    - mmcv==1.3.9
    - mmsegmentation==0.16.0
    - nnunet==1.7.0
    - segmentation-models==1.0.1
    - tensorflow-cpu==2.6.0
    - ttach==0.0.3