name: condaenv
channels:
  - conda-forge
  - fastai
dependencies:
  - albumentations=1.0.3
  - fastai=2.5.0
  - imageio=2.9.0
  - keras=2.6.0
  - loguru=0.5.3
  - mkl=2020.4
  - numpy=1.20.3
  - numba=0.54.1
  - opencv=4.5.2
  - pandas=1.2.5
  - pillow=8.2.0
  - pip=20.3.4
  - pytest=6.2.4
  - python=3.9.7
  - pytorch-cpu=1.8.0
  - pytorch-lightning=1.4.1
  - scikit-image=0.18.2
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - timm=0.4.12
  - torchvision=0.9.1
  - tqdm=4.62.0
  - pip:
    - lightning-flash[image]==0.5.0
    - tensorflow-cpu==2.6.0
