
name: Build and publish image

on:
  push:
    branches: [master]
    paths: ['runtime/**', '.github/workflows/build-image.yml']
  pull_request:
    paths: ['runtime/**', '.github/workflows/build-image.yml']

jobs:
  build:
    name: Build, Test, and Publish Image
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        proc: ['cpu', 'gpu']
    env:
      IMAGE: drivendata/belugas-competition
      SHA_TAG: ${{ matrix.proc }}-${{ github.sha }}
      LATEST_TAG: ${{ matrix.proc }}-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        run: |
          docker build runtime \
            --build-arg CPU_OR_GPU=${{ matrix.proc }} \
            --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/$IMAGE:$SHA_TAG \
            --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/$IMAGE:$LATEST_TAG

      - name: Tests packages in container
        run: |
          docker run ${{ secrets.REGISTRY_LOGIN_SERVER }}/$IMAGE:$SHA_TAG /bin/bash \
            -c "conda run --no-capture-output -n condaenv pytest tests/test_packages.py"

      - name: Log into Azure
        if: github.ref == 'refs/heads/master'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log into ACR with Docker
        if: github.ref == 'refs/heads/master'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push image to ACR
        if: github.ref == 'refs/heads/master'
        run: |
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$IMAGE:$SHA_TAG
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$IMAGE:$LATEST_TAG
