
name: Build and publish container

on:
  push:
    branches: [master, setup]
    paths: ['runtime/**', '.github/workflows/build-containers.yml']
  pull_request:
    paths: ['runtime/**', '.github/workflows/build-containers.yml']

jobs:
  build:
    name: Build, Test, Publish Container
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
    env:
      CONTAINER: boembelugas.azurecr.io/test
      SHA_TAG: ${{ github.sha }}
      LATEST_TAG: latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Container
        run: |
          docker build runtime --tag $CONTAINER:$LATEST_TAG

#      - name: Tests container packages
#        run: |
#          docker run --mount type=bind,source=$(pwd)/runtime/run-tests.sh,target=/run-tests.sh,readonly \
#            --mount type=bind,source=$(pwd)/runtime/tests,target=/tests,readonly \
#            $CONTAINER:$SHA_TAG \
#            /bin/bash -c "source activate py; python tests/test_installs.py"

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Push image to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$CONTAINER:$LATEST_TAG
