
name: Build and publish container

on:
  push:
    branches: [master]
    paths: ['runtime/**', '.github/workflows/build-containers.yml']
  pull_request:
    paths: ['runtime/**', '.github/workflows/build-containers.yml']

jobs:
  build:
    name: Build, Test, Publish Container
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        proc: ['cpu', 'gpu']
    env:
      CONTAINER: drivendata/belugas-competition
      SHA_TAG: ${{ github.sha }}
      LATEST_TAG: latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Container
        run: |
          docker build runtime --build-arg CPU_OR_GPU=${{ matrix.proc }} --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/$CONTAINER:$SHA_TAG
          docker build runtime --build-arg CPU_OR_GPU=${{ matrix.proc }} --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/$CONTAINER:$LATEST_TAG

      - name: Tests container packages
        run: |
          docker run ${{ secrets.REGISTRY_LOGIN_SERVER }}/$CONTAINER:$SHA_TAG /bin/bash -c "conda run --no-capture-output -n condaenv pytest tests/test_packages.py"

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Push image to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$CONTAINER:$SHA_TAG
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$CONTAINER:$LATEST_TAG
